FTS:
  r01:
    edges:
    - cost: 1.0
      target: r01
    - cost: 1.0
      target: r02
    pose:
      orientation:
      - 0.7005300336152545
      - 0.0
      - 0.0
      - 0.7136229200376137
      position:
      - 1.96
      - 1.4000000000000001
      - 0.0
    propos:
    - r01
  r02:
    edges:
    - cost: 1.0
      target: r01
    - cost: 1.0
      target: r02
    - cost: 1.0
      target: r03
    - cost: 1.0
      target: r27
    pose:
      orientation:
      - 1.0
      - 0.0
      - 0.0
      - 0.0
      position:
      - 1.56
      - 2.44
      - 0.0
    propos:
    - r02
  r03:
    edges:
    - cost: 1.0
      target: r02
    - cost: 1.0
      target: r03
    - cost: 1.0
      target: r04
    pose:
      orientation:
      - 0.7071067811865476
      - 0.0
      - 0.0
      - 0.7071067811865475
      position:
      - 1.58
      - 5.08
      - 0.0
    propos:
    - r03
  r04:
    edges:
    - cost: 1.0
      target: r03
    - cost: 1.0
      target: r04
    - cost: 1.0
      target: r05
    - cost: 1.0
      target: r06
    pose:
      orientation:
      - 1.0
      - 0.0
      - 0.0
      - 0.0
      position:
      - 3.04
      - 7.04
      - 0.0
    propos:
    - r04
  r05:
    edges:
    - cost: 1.0
      target: r04
    - cost: 1.0
      target: r05
    pose:
      orientation:
      - 0.7210991742988171
      - -0.0
      - -0.0
      - -0.6928318560989847
      position:
      - 3.02
      - 8.36
      - 0.0
    propos:
    - r05
  r06:
    edges:
    - cost: 1.0
      target: r04
    - cost: 1.0
      target: r06
    - cost: 1.0
      target: r07
    - cost: 1.0
      target: r08
    pose:
      orientation:
      - 0.9999409454622599
      - -0.0
      - -0.0
      - -0.010867639488034079
      position:
      - 5.44
      - 7.0200000000000005
      - 0.0
    propos:
    - r06
  r07:
    edges:
    - cost: 1.0
      target: r06
    - cost: 1.0
      target: r07
    pose:
      orientation:
      - 0.8484890832562502
      - 0.0
      - 0.0
      - 0.5292128830583853
      position:
      - 5.04
      - 5.04
      - 0.0
    propos:
    - r07
  r08:
    edges:
    - cost: 1.0
      target: r06
    - cost: 1.0
      target: r08
    - cost: 1.0
      target: r09
    - cost: 1.0
      target: r10
    pose:
      orientation:
      - 1.0
      - 0.0
      - 0.0
      - 0.0
      position:
      - 7.5200000000000005
      - 7.08
      - 0.0
    propos:
    - r08
  r09:
    edges:
    - cost: 1.0
      target: r08
    - cost: 1.0
      target: r09
    pose:
      orientation:
      - 0.701730084756145
      - -0.0
      - -0.0
      - -0.7124429016757299
      position:
      - 7.5
      - 8.44
      - 0.0
    propos:
    - r09
  r10:
    edges:
    - cost: 1.0
      target: r08
    - cost: 1.0
      target: r10
    - cost: 1.0
      target: r11
    - cost: 1.0
      target: r12
    - cost: 1.0
      target: r22
    pose:
      orientation:
      - 0.999532649182912
      - -0.0
      - -0.0
      - -0.03056931823560688
      position:
      - 11.5
      - 7.08
      - 0.0
    propos:
    - r10
  r11:
    edges:
    - cost: 1.0
      target: r10
    pose:
      orientation:
      - 0.7071067811865476
      - -0.0
      - -0.0
      - -0.7071067811865475
      position:
      - 11.44
      - 8.46
      - 0.0
    propos:
    - r11
  r12:
    edges:
    - cost: 1.0
      target: r10
    - cost: 1.0
      target: r12
    - cost: 1.0
      target: r13
    - cost: 1.0
      target: r14
    pose:
      orientation:
      - 1.0
      - 0.0
      - 0.0
      - 0.0
      position:
      - 14.44
      - 7.0600000000000005
      - 0.0
    propos:
    - r12
  r13:
    edges:
    - cost: 1.0
      target: r12
    - cost: 1.0
      target: r13
    pose:
      orientation:
      - 0.699855729896341
      - 0.0
      - 0.0
      - 0.7142842272731911
      position:
      - 13.92
      - 4.34
      - 0.0
    propos:
    - r13
  r14:
    edges:
    - cost: 1.0
      target: r12
    - cost: 1.0
      target: r14
    - cost: 1.0
      target: r15
    - cost: 1.0
      target: r16
    pose:
      orientation:
      - 0.7137452511042065
      - -0.0
      - -0.0
      - -0.7004053944154008
      position:
      - 17.52
      - 7.0600000000000005
      - 0.0
    propos:
    - r14
  r15:
    edges:
    - cost: 1.0
      target: r14
    pose:
      orientation:
      - 0.7026175297231787
      - -0.0
      - -0.0
      - -0.7115677107104411
      position:
      - 17.54
      - 8.46
      - 0.0
    propos:
    - r15
  r16:
    edges:
    - cost: 1.0
      target: r14
    - cost: 1.0
      target: r16
    - cost: 1.0
      target: r17
    - cost: 1.0
      target: r19
    pose:
      orientation:
      - 0.7071067811865476
      - -0.0
      - -0.0
      - -0.7071067811865475
      position:
      - 16.94
      - 4.5
      - 0.0
    propos:
    - r16
  r17:
    edges:
    - cost: 1.0
      target: r16
    - cost: 1.0
      target: r17
    pose:
      orientation:
      - 6.123233995736766e-17
      - 0.0
      - 0.0
      - 1.0
      position:
      - 19.1
      - 4.5200000000000005
      - 0.0
    propos:
    - r17
  r18:
    edges:
    - cost: 1.0
      target: r18
    - cost: 1.0
      target: r19
    pose:
      orientation:
      - 0.7182374422274201
      - 0.0
      - 0.0
      - 0.6957980860728299
      position:
      - 17.52
      - 0.9400000000000001
      - 0.0
    propos:
    - r18
  r19:
    edges:
    - cost: 1.0
      target: r16
    - cost: 1.0
      target: r18
    - cost: 1.0
      target: r19
    - cost: 1.0
      target: r20
    pose:
      orientation:
      - 0.7071067811865476
      - 0.0
      - 0.0
      - 0.7071067811865475
      position:
      - 16.94
      - 2.74
      - 0.0
    propos:
    - r19
  r20:
    edges:
    - cost: 1.0
      target: r19
    - cost: 1.0
      target: r20
    - cost: 1.0
      target: r21
    pose:
      orientation:
      - 0.7002759405293947
      - -0.0
      - -0.0
      - -0.7138722624641411
      position:
      - 15.02
      - 2.42
      - 0.0
    propos:
    - r20
  r21:
    edges:
    - cost: 1.0
      target: r20
    - cost: 1.0
      target: r21
    pose:
      orientation:
      - 0.6943732675901296
      - 0.0
      - 0.0
      - 0.7196150118335541
      position:
      - 15.040000000000001
      - 0.62
      - 0.0
    propos:
    - r21
  r22:
    edges:
    - cost: 1.0
      target: r10
    - cost: 1.0
      target: r22
    - cost: 1.0
      target: r23
    - cost: 1.0
      target: r24
    pose:
      orientation:
      - 0.9999783613013082
      - -0.0
      - -0.0
      - -0.006578520285761062
      position:
      - 10.88
      - 1.62
      - 0.0
    propos:
    - r22
  r23:
    edges:
    - cost: 1.0
      target: r22
    - cost: 1.0
      target: r23
    pose:
      orientation:
      - 0.0066662222732440865
      - -0.0
      - -0.0
      - -0.9999777804934487
      position:
      - 13.08
      - 1.54
      - 0.0
    propos:
    - r23
  r24:
    edges:
    - cost: 1.0
      target: r22
    - cost: 1.0
      target: r24
    - cost: 1.0
      target: r25
    - cost: 1.0
      target: r26
    - cost: 1.0
      target: r27
    pose:
      orientation:
      - 0.9998348608511388
      - -0.0
      - -0.0
      - -0.018172810095963155
      position:
      - 8.540000000000001
      - 2.02
      - 0.0
    propos:
    - r24
  r25:
    edges:
    - cost: 1.0
      target: r24
    - cost: 1.0
      target: r25
    pose:
      orientation:
      - 0.7071067811865476
      - 0.0
      - 0.0
      - 0.7071067811865475
      position:
      - 8.48
      - 0.58
      - 0.0
    propos:
    - r25
  r26:
    edges:
    - cost: 1.0
      target: r24
    - cost: 1.0
      target: r26
    pose:
      orientation:
      - 0.6995456448686619
      - -0.0
      - -0.0
      - -0.714587916736134
      position:
      - 7.94
      - 4.68
      - 0.0
    propos:
    - r26
  r27:
    edges:
    - cost: 1.0
      target: r02
    - cost: 1.0
      target: r24
    - cost: 1.0
      target: r27
    - cost: 1.0
      target: r28
    pose:
      orientation:
      - 0.7122865618702476
      - -0.0
      - -0.0
      - -0.7018887759318152
      position:
      - 4.98
      - 2.62
      - 0.0
    propos:
    - r27
  r28:
    edges:
    - cost: 1.0
      target: r27
    pose:
      orientation:
      - 0.7129741763675572
      - 0.0
      - 0.0
      - 0.7011902907435352
      position:
      - 5.04
      - 0.76
      - 0.0
    propos:
    - r28
