FTS:
  r01:
    edges:
    - cost: 1.0
      target: r01
    - cost: 1.0
      target: r02
    pose:
      orientation:
      - 1.0
      - -0.0
      - -0.0
      - -0.0
      position:
      - 0.0
      - 0.0
      - 0.0
  r02:
    edges:
    - cost: 1.0
      target: r01
    - cost: 1.0
      target: r02
    pose:
      orientation:
      - 0.9238795325112867
      - -0.0
      - -0.0
      - -0.3826834323650898
      position:
      - -1.1500000000000001
      - -0.9999999999999987
      - 0.0
Map: sml
Tasks:
  robot1:
    initial_pose: r01
    robot_model: Turtlebot
    tasks:
      hard_task: ([]<> r01) && ([]<> r02)
      soft_task: ''
